### ISSUE TITLE
ImportError: No module named batch_norm_utils

### ISSUE THREAD

**Issue by cardwing** [spiglerg/DQN_and_DDPG_Tensorflow#1]
Hi, spiglerg! When I run gym_ddpg.py, it raises an error:ImportError: No module named batch_norm_utils. It is obvious that batch_norm_utils.py is not included in the DQN_DDQN_Dueling_and_DDPG_Tensorflow file which uses batch normalization in the network. Have you missed this file when passing the package? Thanks a lot! 
Regards,
Cardwing

**Comment by spiglerg** [comment]
Thank you very much for letting me know!
Indeed, I have more extensive local files with different models that I am working on, but it is not all included in this repository. :)
I have fixed the error and committed. It should now work fine!
